# Generated by Django 4.2.3 on 2023-08-02 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('day', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], default='1', max_length=2)),
                ('month', models.CharField(choices=[('JAN', 'January'), ('FEB', 'February'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], default='JAN', max_length=9)),
                ('year', models.CharField(max_length=4)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('Deposit', 'Deposit'), ('Expense', 'Expense'), ('Investment', 'Investment')], default='EXPENSE', max_length=10)),
                ('category', models.CharField(choices=[('Going out & Eating out', 'Going out & Eating out'), ('Car, Gas, & Auto Insurance', 'Car, Gas, & Auto Insurance'), ('Rent & Utilities', 'Rent & Utilities'), ('Travel, Personal, & Other', 'Travel, Personal, & Other'), ('Loans', 'Loans'), ('Savings & Investments', 'Savings & Investments'), ('Subscriptions', 'Subscriptions'), ('Groceries', 'Groceries'), ('Paycheck & Deposits', 'Paycheck & Deposits')], default='OTHER', max_length=75)),
                ('account', models.CharField(blank=True, max_length=10, null=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
