# Generated by Django 4.2.3 on 2023-08-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Going out & Eating out', 'Going out & Eating out'), ('Car, Gas, & Auto Insurance', 'Car, Gas, & Auto Insurance'), ('Rent & Utilities', 'Rent & Utilities'), ('Travel, Personal, & Other', 'Travel, Personal, & Other'), ('Loans', 'Loans'), ('Savings & Investments', 'Savings & Investments'), ('Subscriptions', 'Subscriptions'), ('Groceries', 'Groceries'), ('Paycheck & Deposits', 'Paycheck & Deposits')], default='Travel, Personal, & Other', max_length=75),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='month',
            field=models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], default='Jan', max_length=9),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Expense', 'Expense'), ('Investment', 'Investment')], default='Expense', max_length=10),
        ),
    ]
