# Generated by Django 4.2.3 on 2023-12-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_transaction_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='day',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='month',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='year',
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
