# Generated by Django 4.2.3 on 2023-12-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_transaction_day_remove_transaction_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
