# Generated by Django 4.2.3 on 2023-12-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Investment', 'Investment')], default='Expense', max_length=10),
        ),
    ]
