const transactions = [
    {
        'id': '1',
        'category': 'Going Out and Eating Out',
        'amount': 100.00,
        'type': 'expense',
        'description': 'Food',
        'month': 'July',
        'day': '23',
        'year': '2023',
    },
    {
        'id': '2',
        'category': 'Paycheck and Deposits',
        'amount': 3000.00,
        'type': 'income',
        'description': 'July paycheck',
        'month': 'July',
        'day': '12',
        'year': '2023',
    },
    {
        'id': '3',
        'category': 'Rent and Utilities',
        'amount': 1050.00,
        'type': 'expense',
        'description': 'July Rent',
        'month': 'July',
        'day': '02',
        'year': '2023',
    },
    {
        'id': '4',
        'category': 'Investments',
        'amount': 540.00,
        'type': 'investment',
        'description': 'Roth IRA contribution',
        'month': 'July',
        'day': '14',
        'year': '2023',
    },
    {
        'id': '5',
        'category': 'Subscriptions',
        'amount': 15.99,
        'type': 'expense',
        'description': 'HBO Max',
        'month': 'July',
        'day': '23',
        'year': '2023',
    },
    {
        'id': '6',
        'category': 'Gas',
        'amount': 46.23,
        'type': 'expense',
        'description': 'Gas',
        'month': 'July',
        'day': '22',
        'year': '2023',
        
    },
    {
        'id': '7',
        'category': 'Going Out and Eating Out',
        'amount': 12.62,
        'type': 'expense',
        'description': 'Chipotle',
        'month': 'July',
        'day': '22',
        'year': '2023',
        
    },
    {
        'id': '8',
        'category': 'Going Out and Eating Out',
        'amount': 320.12,
        'type': 'expense',
        'description': 'Target',
        'month': 'August',
        'day': '02',
        'year': '2023',
        
    },
    {
        'id': '9',
        'category': 'Savings and Investments',
        'amount': 600.00,
        'type': 'investment',
        'description': 'August Savings Transfer',
        'month': 'August',
        'day': '13',
        'year': '2023',
        
    },
    {
        'id': '10',
        'category': 'Paycheck and Deposits',
        'amount': 3205,
        'type': 'income',
        'description': 'Monthly Paycheck',
        'month': 'August',
        'day': '04',
        'year': '2023',
        
    },


]

export default transactions;